import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared-comp/navbar";
import Cursor from "@/shared-comp/cursor";
import Contact from "@/shared-comp/contact";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} text-slate-900 bg-slate-50 antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-slate-50 font-sans">
        <Navbar />
        <Cursor />
        {children}

        <div className="bg-white">
          <Contact />
        </div>
      </body>
    </html>
  );
}